import { ContentItem } from './types';

export const CONTENT_ITEMS: ContentItem[] = [
  {
    id: 50,
    title: 'Spider-Man: Across the Spider-Verse',
    year: 2023,
    genre: 'Animation, Action, Adventure',
    type: 'Movie',
    description: 'After reuniting with Gwen Stacy, Brooklyn’s full-time, friendly neighborhood Spider-Man is catapulted across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence. When the heroes clash on how to handle a new threat, Miles finds himself pitted against the other Spiders and must redefine what it means to be a hero.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    quality: '4K',
    rating: 8.4,
  },
  {
    id: 51,
    title: 'Oppenheimer',
    year: 2023,
    genre: 'Drama, History',
    type: 'Movie',
    description: 'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    quality: '4K',
    rating: 8.1,
  },
  {
    id: 52,
    title: 'The Queen\'s Gambit',
    year: 2020,
    genre: 'Drama',
    type: 'TV Series',
    description: 'In a 1950s orphanage, a young girl reveals an astonishing talent for chess and begins an unlikely journey to stardom while grappling with addiction.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/zU0htwEjIFnwsCopYLMA2wdEcAq.jpg',
    quality: 'HD',
    rating: 8.6,
  },
  {
    id: 53,
    title: 'Interstellar',
    year: 2014,
    genre: 'Adventure, Drama, Sci-Fi',
    type: 'Movie',
    description: 'A team of explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    quality: '4K',
    rating: 8.7,
  },
  {
    id: 54,
    title: 'The Last of Us',
    year: 2023,
    genre: 'Drama, Action, Adventure',
    type: 'TV Series',
    description: 'After a global pandemic destroys civilization, a hardened survivor takes charge of a 14-year-old girl who may be humanity\'s last hope.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg',
    quality: 'HD',
    rating: 8.7,
  },
  {
    id: 55,
    title: 'Dune',
    year: 2021,
    genre: 'Sci-Fi, Adventure',
    type: 'Movie',
    description: 'A noble family becomes embroiled in a war for control over the galaxy\'s most valuable asset while its heir becomes troubled by visions of a dark future.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/d5NXSklXo0qyIY2VhrhTnucflza.jpg',
    quality: '4K',
    rating: 7.8,
  },
  {
    id: 56,
    title: 'The Bear',
    year: 2022,
    genre: 'Comedy, Drama',
    type: 'TV Series',
    description: 'A young chef from the fine dining world returns to Chicago to run his family sandwich shop.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/6vZeVAzctBwrVrolssthT6P4D6.jpg',
    quality: 'HD',
    rating: 8.5,
  },
  {
    id: 57,
    title: 'The Matrix',
    year: 1999,
    genre: 'Action, Sci-Fi',
    type: 'Movie',
    description: 'When a beautiful stranger leads computer hacker Neo to a forbidding underworld, he discovers the shocking truth--the life he knows is the elaborate deception of an evil cyber-intelligence.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdU4SSTJYga.jpg',
    quality: 'Blu-Ray',
    rating: 8.2,
  },
  {
    id: 58,
    title: 'Succession',
    year: 2018,
    genre: 'Drama',
    type: 'TV Series',
    description: 'The Roy family is known for controlling the biggest media and entertainment company in the world. However, their world changes when their father steps down from the company.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/hH44Vlo3HP36gQ4a22yS53sSgA5.jpg',
    quality: 'WEB-DL',
    rating: 8.7,
  },
  {
    id: 59,
    title: 'Forrest Gump',
    year: 1994,
    genre: 'Drama, Comedy, Romance',
    type: 'Movie',
    description: 'The presidencies of Kennedy and Johnson, the Vietnam War, the Watergate scandal and other historical events unfold from the perspective of an Alabama man with an IQ of 75, whose only desire is to be reunited with his childhood sweetheart.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/arw2vcBveWOVZr6pxd9XTd1TdSm.jpg',
    quality: '4K',
    rating: 8.5,
  },
  {
    id: 60,
    title: 'Severance',
    year: 2022,
    genre: 'Drama, Mystery, Sci-Fi',
    type: 'TV Series',
    description: 'Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives. When a mysterious colleague appears outside of work, it begins a journey to discover the truth about their jobs.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/lFf6LLr96dH09RBYcvB1mEEs2V2.jpg',
    quality: 'HD',
    rating: 8.3,
  },
  {
    id: 61,
    title: 'Gladiator',
    year: 2000,
    genre: 'Action, Drama, Adventure',
    type: 'Movie',
    description: 'A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg',
    quality: '4K',
    rating: 8.2,
  },
  {
    id: 62,
    title: 'Ted Lasso',
    year: 2020,
    genre: 'Comedy, Drama, Sport',
    type: 'TV Series',
    description: 'American college football coach Ted Lasso is recruited to coach an English soccer team in an attempt by its owner to spite her ex-husband. Lasso tries to win over the skeptical English market with his folksy, optimistic demeanor while dealing with his inexperience in the sport.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/5fhZdedsyRGACD3NBzP86u18JzC.jpg',
    quality: 'HD',
    rating: 8.5,
  },
  {
    id: 63,
    title: 'The Silence of the Lambs',
    year: 1991,
    genre: 'Crime, Drama, Thriller',
    type: 'Movie',
    description: 'A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/uS9m8fnpKNrVz21jOn9m3oO2m02.jpg',
    quality: 'BRRIP',
    rating: 8.3,
  },
  {
    id: 64,
    title: 'Chernobyl',
    year: 2019,
    genre: 'Drama, History',
    type: 'TV Series',
    description: 'In April 1986, an explosion at the Chernobyl nuclear power plant in the Union of Soviet Socialist Republics becomes one of the world\'s worst man-made catastrophes.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/hlLXt2tOPT6RRnjiUmoxyG1LTqu.jpg',
    quality: 'HD',
    rating: 8.8,
  },
  {
    id: 65,
    title: 'Fight Club',
    year: 1999,
    genre: 'Drama',
    type: 'Movie',
    description: 'An insomniac office worker looking for a way to change his life crosses paths with a devil-may-care soap maker and they form an underground fight club that evolves into something much, much more.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
    quality: 'Blu-Ray',
    rating: 8.4,
  },
  {
    id: 66,
    title: 'The Mandalorian',
    year: 2019,
    genre: 'Sci-Fi & Fantasy, Action, Adventure',
    type: 'TV Series',
    description: 'After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy. A lone gunfighter makes his way through the outer reaches, earning his keep as a bounty hunter.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/eU1i6eLXPvHWNO69l3Q6n4yIbM2.jpg',
    quality: 'HDTV',
    rating: 8.5,
  },
  {
    id: 67,
    title: 'Goodfellas',
    year: 1990,
    genre: 'Drama, Crime',
    type: 'Movie',
    description: 'The story of Henry Hill and his life in the mob, covering his relationship with his wife Karen Hill and his mob partners Jimmy Conway and Tommy DeVito in the Italian-American crime syndicate.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkReRdLaw.jpg',
    quality: '4K',
    rating: 8.5,
  },
  {
    id: 68,
    title: 'The Wire',
    year: 2002,
    genre: 'Crime, Drama',
    type: 'TV Series',
    description: 'The drug scene in Baltimore as seen through the eyes of drug dealers and law enforcement officers.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/4lbFpFxAc7EknAEVbApWuJmq0Ct.jpg',
    quality: 'HD',
    rating: 8.8,
  },
  {
    id: 69,
    title: 'The Sopranos',
    year: 1999,
    genre: 'Drama, Crime',
    type: 'TV Series',
    description: 'New Jersey mob boss Tony Soprano deals with personal and professional issues in his home and business life that affect his mental state, leading him to seek professional psychiatric counseling.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/rTc7sCVi2dG7LwGWo48D5s26aTE.jpg',
    quality: 'HD',
    rating: 8.7,
  },
  {
    id: 70,
    title: 'The Shawshank Redemption',
    year: 1994,
    genre: 'Drama, Crime',
    type: 'Movie',
    description: 'Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
    quality: '4K',
    rating: 9.3,
  },
  {
    id: 71,
    title: 'The Godfather',
    year: 1972,
    genre: 'Drama, Crime',
    type: 'Movie',
    description: 'The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    quality: '4K',
    rating: 9.2,
  },
  {
    id: 72,
    title: 'The Dark Knight',
    year: 2008,
    genre: 'Action, Crime, Drama',
    type: 'Movie',
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    quality: '4K',
    rating: 9.0,
  },
  {
    id: 73,
    title: 'Pulp Fiction',
    year: 1994,
    genre: 'Thriller, Crime',
    type: 'Movie',
    description: 'The lives of two mob hitmen, a boxer, a gangster and his wife, and a pair of diner bandits intertwine in four tales of violence and redemption.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    quality: '4K',
    rating: 8.9,
  },
  {
    id: 74,
    title: 'Breaking Bad',
    year: 2008,
    genre: 'Crime, Drama, Thriller',
    type: 'TV Series',
    description: 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/ggFHVNu6YYI5L9pCfOacjizRGt.jpg',
    quality: 'HD',
    rating: 9.5,
  },
  {
    id: 75,
    title: 'Game of Thrones',
    year: 2011,
    genre: 'Sci-Fi & Fantasy, Drama, Action',
    type: 'TV Series',
    description: 'Nine noble families fight for control over the lands of Westeros, while an ancient enemy returns after being dormant for millennia.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1XS1oqL89wqnXjmQg9452hU1fTO.jpg',
    quality: 'HD',
    rating: 8.4,
  },
  {
    id: 76,
    title: 'Inception',
    year: 2010,
    genre: 'Action, Sci-Fi, Adventure',
    type: 'Movie',
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq27gApcjBJUuNXwg.jpg',
    quality: '4K',
    rating: 8.4,
  },
  {
    id: 77,
    title: 'Stranger Things',
    year: 2016,
    genre: 'Sci-Fi & Fantasy, Mystery, Drama',
    type: 'TV Series',
    description: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    quality: 'HD',
    rating: 8.6,
  },
  {
    id: 78,
    title: 'Parasite',
    year: 2019,
    genre: 'Comedy, Thriller, Drama',
    type: 'Movie',
    description: 'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    quality: '4K',
    rating: 8.5,
  },
  {
    id: 79,
    title: 'The Office',
    year: 2005,
    genre: 'Comedy',
    type: 'TV Series',
    description: 'A mockumentary on a group of typical office workers, where the workday consists of ego clashes, inappropriate behavior, and tedium.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/qWnJzyZhyy74gjpSjIXWmuk0ifX.jpg',
    quality: 'HD',
    rating: 8.6,
  },
  {
    id: 80,
    title: 'Fleabag',
    year: 2016,
    genre: 'Comedy, Drama',
    type: 'TV Series',
    description: 'A comedic and poignant look at a dry-witted woman, known only as Fleabag, as she navigates life and love in London while trying to cope with tragedy.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/27vEYsRKa3eAnEqO3t5d2aBza42.jpg',
    quality: 'HD',
    rating: 8.3,
  },
  {
    id: 81,
    title: 'Joker',
    year: 2019,
    genre: 'Crime, Thriller, Drama',
    type: 'Movie',
    description: 'In Gotham City, mentally troubled comedian Arthur Fleck is disregarded and mistreated by society. He then embarks on a downward spiral of revolution and bloody crime.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg',
    quality: '4K',
    rating: 8.2,
  },
  {
    id: 82,
    title: 'The Boys',
    year: 2019,
    genre: 'Sci-Fi & Fantasy, Action',
    type: 'TV Series',
    description: 'A group of vigilantes set out to take down corrupt superheroes who abuse their superpowers.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/2zmTngn1tJSCpknrSg22e7aKzBf.jpg',
    quality: 'HD',
    rating: 8.5,
  },
  {
    id: 83,
    title: 'Blade Runner 2049',
    year: 2017,
    genre: 'Sci-Fi, Drama',
    type: 'Movie',
    description: 'Young Blade Runner K\'s discovery of a long-buried secret leads him to track down former Blade Runner Rick Deckard, who\'s been missing for thirty years.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
    quality: '4K',
    rating: 7.9,
  },
  {
    id: 84,
    title: 'Rick and Morty',
    year: 2013,
    genre: 'Animation, Comedy, Sci-Fi',
    type: 'TV Series',
    description: 'An animated series that follows the exploits of a super scientist and his not-so-bright grandson.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/cvhNj9eoRBe5SxjCbQTkh05UP5K.jpg',
    quality: 'HD',
    rating: 8.7,
  }
];